### PR TITLE
Refactor resourceBigipLtmNodeDelete

### PR DESCRIPTION
**Pull request by dannyk81**
This is an attempt to make the Node delete function usable, at the moment deleting a node results in an endless loop.

This PR doesn't solve https://github.com/f5devcentral/terraform-provider-bigip/issues/87, however considering how the nodes and pools are tied together, I couldn't find a better approach.

One option might be to manage the pool membership in a separate resource.

This PR handles the following issues:
1) Current implementation deletes **all** members in the pool where the to-be-destroyed node is a member - fixed.
2) The regex to locate the pool name in the error message was wrong, it needs to include the partition name (this is what was causing the endless loop) - fixed.
3) Some formatting

I performed few tests and this seems to work well, however I agree with @fcgravalos that this function implementation needs to be reviewed further.

### CODE REVIEW

**Comment by dannyk81** [comment]
Here's a log for deleting a node (/<partition-name>/blue-kubl-03):
```
module.kubespray_blue.bigip_ltm_node.ingress_node[2]: Destroying... (ID: /<partition-name>/blue-kubl-03)
2018-05-30T05:05:02.604Z [DEBUG] plugin.terraform-provider-bigip: 2018/05/30 05:05:02 [INFO] Deleting node /<partition-name>/blue-kubl-03
2018-05-30T05:05:02.642Z [DEBUG] plugin.terraform-provider-bigip: 2018/05/30 05:05:02 [INFO] Deleting node /<partition-name>/blue-kubl-03 from pool /<partition-name>/blue_kub_ingress_pool...
2018-05-30T05:05:02.683Z [DEBUG] plugin.terraform-provider-bigip: 2018/05/30 05:05:02 [INFO] Checking if /<partition-name>/blue-kubl-01:80 contains /<partition-name>/blue-kubl-03
2018-05-30T05:05:02.683Z [DEBUG] plugin.terraform-provider-bigip: 2018/05/30 05:05:02 [INFO] Checking if /<partition-name>/blue-kubl-02:80 contains /<partition-name>/blue-kubl-03
2018-05-30T05:05:02.683Z [DEBUG] plugin.terraform-provider-bigip: 2018/05/30 05:05:02 [INFO] Checking if /<partition-name>/blue-kubl-03:80 contains /<partition-name>/blue-kubl-03
module.kubespray_blue.bigip_ltm_node.ingress_node[2]: Destruction complete after 0s
module.kubespray_blue.bigip_ltm_pool.kub_ingress_pool: Modifying... (ID: /NOVUM_PRE_MOVES_APP/blue_kub_ingress_pool)
  nodes.#:          "3" => "2"
  nodes.1904996906: "/<partition-name>/blue-kubl-03:80" => ""
  nodes.3375863119: "/<partition-name>/blue-kubl-02:80" => "/<partition-name>/blue-kubl-02:80"
  nodes.3682744993: "/<partition-name>/blue-kubl-01:80" => "/<partition-name>/blue-kubl-01:80"
2018-05-30T05:05:03.032Z [DEBUG] plugin.terraform-provider-bigip: 2018/05/30 05:05:03 [INFO] Reading pool /<partition-name>/blue_kub_ingress_pool
module.kubespray_blue.bigip_ltm_pool.kub_ingress_pool: Modifications complete after 0s (ID: /<partition-name>/blue_kub_ingress_pool)
```

**Comment by fcgravalos** [comment]
I am thinking that maybe we should add a poolAttachment resource to manage the node membership in a pool. Like in AWS provider when you manage how and instance joins ("attaches to") an ELB.

Such resource should receive the pool and the node, check if both of them exists, add the node as a member of the pool on create and take the node out of the pool on delete.

**Comment by dannyk81** [comment]
@fcgravalos, yes - that sounds like a solid approach and is what I meant by "One option might be to manage the pool membership in a separate resource."

**Comment by bpoland** [comment]
Yes that would be awesome.  I have added provisioners to my bigip_ltm_node which SSHes to the big-ip and runs tmsh to add/remove the nodes from the pool, but a native resource to do that would be great!

**Comment by dannyk81** [comment]
@bpoland for what it's worth, with this PR you get correct handling of adding and removing nodes (and their pool membership) so you should not need provisioners to handle that.

Going forward, it seems there are two options:
1) As suggested by @fcgravalos and myself - create a `resourceBigipLtmPoolAttachment` resource that will manage the attachment of a node to a pool, this seems simple (?) and straightforward.

2) Keep the attachment implementation in-line (add/remove), however the logic of `resourceBigipLtmNodeDelete` should probably be revisited.

@scshitole would love to hear your thoughts on this.

**Comment by bpoland** [comment]
Sorry I should have been more specific.  The way we have things organized, we want to create a pool in a separate terraform config from where we add/remove pool members.  This is to handle upgrades -- we have a separate terraform config for each version and want to create the "new" version (and add those nodes to the pool) before we remove the "old" version (and remove those nodes from the pool).

So I would love to see option 1 -- have a separate resource (e.g. bigip_ltm_pool_attachment or something) that would allow you to manage adding a node to a pool outside of the pool creation.  Or add an option to bigip_ltm_node that specifies what pool(s) the node should be a member of.

**Comment by dannyk81** [comment]
@bpoland thanks for clarifying, indeed this sounds like an interesting use cases and would be gracefully handled via a separate attachment resource.

**Comment by dannyk81** [comment]
This is no longer relevant, this was fixed in https://github.com/f5devcentral/terraform-provider-bigip/pull/93 by introducing a new resource to manage pool attachment.

**Pull request closed without merging**
