### PR TITLE
Don't set node address when creating a FQDN node.

### PR DESCRIPTION
**Pull request by pteiber**
This is a fix for the note left in #68 about failed acceptance tests.

### CODE REVIEW

**Comment by scshitole** [comment]
@pteiber Thanks

**Comment by scshitole** [comment]
@pteiber 
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ BIGIP_USER=admin BIGIP_PASSWORD=admin BIGIP_HOST=10.192.74.73 TF_ACC=1 go test ./bigip -v -run=TestAccBigipLtmNode
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (4.32s)
=== RUN   TestAccBigipLtmNode_import
--- FAIL: TestAccBigipLtmNode_import (4.21s)
	testing.go:513: Step 0 error: Check failed: Check 1/1 error: Node /Common/test-fqdn-node was not created.
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.01s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.02s)
FAIL
exit status 1
FAIL	github.com/f5devcentral/terraform-provider-bigip/bigip	8.648s
SJC-ML-SHITOLE:terraform-provider-bigip shitole$ 

API logs to BIGIP below
I][18485][13 Mar 2018 11:29:11 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/tm/ltm/node","status":200,"from":"192.168.90.69"}
[I][18486][13 Mar 2018 11:29:11 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"DELETE","uri":"http://localhost:8100/mgmt/tm/ltm/node/~Common~test-node","status":200,"from":"192.168.90.69"}
[I][18487][13 Mar 2018 11:29:11 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/tm/ltm/node","status":200,"from":"192.168.90.69"}
[I][18488][13 Mar 2018 11:29:15 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"DELETE","uri":"http://localhost:8100/mgmt/tm/ltm/node/~Common~test-fqdn-node","status":200,"from":"192.168.90.69"}
[I][18489][13 Mar 2018 11:29:15 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/tm/ltm/node","status":200,"from":"192.168.90.69"}
[I][18490][13 Mar 2018 11:29:19 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"DELETE","uri":"http://localhost:8100/mgmt/tm/ltm/node/~Common~test-node","status":200,"from":"192.168.90.69"}
[I][18491][13 Mar 2018 11:29:19 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/tm/ltm/node","status":200,"from":"192.168.90.69"}
[I][18492][13 Mar 2018 11:29:19 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"DELETE","uri":"http://localhost:8100/mgmt/tm/ltm/node/~Common~test-node","status":200,"from":"192.168.90.69"}

**Comment by scshitole** [comment]
@pteiber 
https://gist.github.com/scshitole/947197ab39abdc713ea07813778e5add

**Comment by scshitole** [comment]
@pteiber  I fixed it the test name was wrong it should be "test-fqdn-test"

**Comment by pteiber** [comment]
Yeah -- I just saw that myself. Actually I think I see another issue. Let me clean up my testing environment (I have to test from a different box than I develop on - think things got a bit out of sync), and make a third attempt at this.

I'm sorry for all the trouble with this.

**Pull request merged**
