### PR TITLE
Persist profile

### PR DESCRIPTION
**Pull request by robloxrob**
Added support to manage four types of persistence profiles. These include source address, destination address, ssl, and cookie persistence profiles. Includes tests and documentation.

### CODE REVIEW

**Comment by scshitole** [comment]
@robloxrob thank you

**Comment by scshitole** [comment]
@robloxrob the tests are failing due to Profile does not exists, would you like to add those as well?
=== RUN   TestBigipLtmPersistenceProfileCookieCreate
--- FAIL: TestBigipLtmPersistenceProfileCookieCreate (1.45s)
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_persistence_profile_cookie.test_ppcookie: 1 error occurred:
		
		* bigip_ltm_persistence_profile_cookie.test_ppcookie: 01020036:3: The requested Persistence Profile (/Common/test-ppcookie) was not found.
=== RUN   TestBigipLtmPersistenceProfileCookieImport
--- FAIL: TestBigipLtmPersistenceProfileCookieImport (1.63s)
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_persistence_profile_cookie.test_ppcookie: 1 error occurred:
		
		* bigip_ltm_persistence_profile_cookie.test_ppcookie: 01020036:3: The requested Persistence Profile (/Common/test-ppcookie) was not found.
=== RUN   TestBigipLtmPersistenceProfileDstAddrCreate
--- FAIL: TestBigipLtmPersistenceProfileDstAddrCreate (1.20s)
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr: 1 error occurred:
		
		* bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr: 01020036:3: The requested Persistence Profile (/Common/test-ppdstaddr) was not found.
=== RUN   TestBigipLtmPersistenceProfileDstAddrImport
--- FAIL: TestBigipLtmPersistenceProfileDstAddrImport (1.16s)
	testing.go:513: Step 0 error: Error applying: 1 error occurred:
		
		* bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr: 1 error occurred:
		
		* bigip_ltm_persistence_profile_dstaddr.test_ppdstaddr: 01020036:3: The requested Persistence Profile (/Common/test-ppdstaddr) was not found.
=== RUN   TestBigipLtmPersistenceProfileSrcAddrCreate
--- FAIL: TestBigipLtmPersistenceProfileSrcAddrCreate (2.42s)
	testing.go:513: Step 0 error: After applying this step, the plan was not empty:
		
		DIFF:
		
		UPDATE: bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr
		  app_service: "" => "none"
		
		STATE:
		
		bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr:
		  ID = /Common/test-ppsrcaddr
		  provider = provider.bigip
		  app_service = 
		  defaults_from = /Common/source_addr
		  hash_algorithm = carp
		  map_proxies = enabled
		  mask = 255.255.255.255
		  match_across_pools = enabled
		  match_across_services = enabled
		  match_across_virtuals = enabled
		  mirror = enabled
		  name = /Common/test-ppsrcaddr
		  override_conn_limit = enabled
		  timeout = 3600
=== RUN   TestBigipLtmPersistenceProfileSrcAddrImport
--- FAIL: TestBigipLtmPersistenceProfileSrcAddrImport (1.99s)
	testing.go:513: Step 0 error: After applying this step, the plan was not empty:
		
		DIFF:
		
		UPDATE: bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr
		  app_service: "" => "none"
		
		STATE:
		
		bigip_ltm_persistence_profile_srcaddr.test_ppsrcaddr:
		  ID = /Common/test-ppsrcaddr
		  provider = provider.bigip
		  app_service = 
		  defaults_from = /Common/source_addr
		  hash_algorithm = carp
		  map_proxies = enabled
		  mask = 255.255.255.255
		  match_across_pools = enabled
		  match_across_services = enabled
		  match_across_virtuals = enabled
		  mirror = enabled
		  name = /Common/test-ppsrcaddr
		  override_conn_limit = enabled
		  timeout = 3600
=== RUN   TestBigipLtmPersistenceProfileSSLCreate
--- FAIL: TestBigipLtmPersistenceProfileSSLCreate (1.88s)
	testing.go:513: Step 0 error: Check failed: Check 1/9 error: SSL Persistence Profile /Common/test-PPSSL does not exist.
=== RUN   TestBigipLtmPersistenceProfileSSLImport
--- FAIL: TestBigipLtmPersistenceProfileSSLImport (1.81s)
	testing.go:513: Step 0 error: Check failed: Check 1/1 error: SSL Persistence Profile /Common/test-PPSSL does not exist.
=== RUN   TestBigipLtmPool_create

**Comment by robloxrob** [comment]
Taking a look now

**Comment by scshitole** [comment]
@robloxrob I checked on the bigip logs its giving 400
[I][7459][15 Feb 2018 14:27:50 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"POST","uri":"http://localhost:8100/mgmt/tm/ltm/persistence/cookie","status":400,"from":"172.18.40.183"}
[I][7460][15 Feb 2018 14:27:50 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"PUT","uri":"http://localhost:8100/mgmt/tm/ltm/persistence/cookie/~Common~test-ppcookie","status":404,"from":"172.18.40.183"}
[I][7461][15 Feb 2018 14:27:51 UTC][ForwarderPassThroughWorker] {"user":"local/admin","method":"DELETE","uri":"http://localhost:8100/mgmt/tm/ltm/persistence/cookie/~Common~test-ppcookie","status":404,"from":"172.18.40.183"}

**Comment by robloxrob** [comment]
Yeah I had the incorrect names specified in what I was creating vs what I was checking for. I also was referencing incorrect parent profiles. I issued a new pull request that fixes the issues.

**Pull request merged**
