### PR TITLE
Bring Go current in Travis

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@scshitole please review

**Comment by scshitole** [comment]
@gliptak  thanks, by the way the provider is already published now https://github.com/terraform-providers/terraform-provider-bigip

**Comment by gliptak** [comment]
@scshitole  I see it and it is already current :)

https://github.com/terraform-providers/terraform-provider-bigip/blob/master/.travis.yml#L8

Thanks

**Comment by gliptak** [comment]
maybe change the README to point users/contributors to the new location?

**Pull request merged**
