### PR TITLE
Datagroup resource

### LINKED ISSUE #95: Add LTM iRule data-group entry resource?
Hi there,

Just wondering if there are plans to add an iRule data group entry resource (e.g bigip_ltm_datagroup_record or something)?  This could be used to add/remove records from a data group.  And it might be nice to have a resource to create data groups as well (e.g. bigip_ltm_datagroup).

Right now I am using a provisioner which SSHes to the big-ip and runs tmsh but it would be great to have native support for this.  Here's an example of the tmsh call I use:

tmsh modify ltm data-group internal /Partition/data_group_name records add { dgl_entry_name { data dgl_entry_value }}

tmsh modify ltm data-group internal /Partition/data_group_name records delete { dgl_entry_name }

Thanks!

### PR DESCRIPTION
**Pull request by dannyk81**
Resource to manage internal (in-line) data groups. Fixes #95 

This is still WIP.

It also depends on few changes to the go-bigip package (will do a separate PR for that)

### CODE REVIEW

**Comment by dannyk81** [comment]
Test are failing due to missing `GetDatagroup` function in go-bigip (I will submit a separate PR for that)

**Comment by dannyk81** [comment]
Tests are passing (with https://github.com/f5devcentral/go-bigip/pull/10), except the infamous iApp tests...

```
=== RUN   TestAccProvider
--- PASS: TestAccProvider (0.02s)
=== RUN   TestAccBigipCmDevice_create
--- PASS: TestAccBigipCmDevice_create (5.76s)
=== RUN   TestAccBigipCmDevice_import
--- PASS: TestAccBigipCmDevice_import (5.16s)
=== RUN   TestAccBigipCmDevicegroup_create
--- PASS: TestAccBigipCmDevicegroup_create (6.24s)
=== RUN   TestAccBigipCmDevicegroup_import
--- PASS: TestAccBigipCmDevicegroup_import (6.32s)
=== RUN   TestAccBigipLtmDataGroup_create
--- PASS: TestAccBigipLtmDataGroup_create (15.75s)
=== RUN   TestAccBigipLtmDataGroup_import
--- PASS: TestAccBigipLtmDataGroup_import (15.83s)
=== RUN   TestAccBigipLtmIRule_create
--- PASS: TestAccBigipLtmIRule_create (5.25s)
=== RUN   TestAccBigipLtmIRule_import
--- PASS: TestAccBigipLtmIRule_import (5.20s)
=== RUN   TestAccBigipLtmMonitor_create
--- PASS: TestAccBigipLtmMonitor_create (11.23s)
=== RUN   TestAccBigipLtmMonitor_import
--- PASS: TestAccBigipLtmMonitor_import (11.16s)
=== RUN   TestAccBigipLtmNode_create
--- PASS: TestAccBigipLtmNode_create (10.49s)
=== RUN   TestAccBigipLtmNode_import
--- PASS: TestAccBigipLtmNode_import (10.50s)
=== RUN   TestAccBigipLtmNodeInvalid
--- PASS: TestAccBigipLtmNodeInvalid (0.02s)
=== RUN   TestAccBigipLtmNodeCreate
--- PASS: TestAccBigipLtmNodeCreate (0.09s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieCreate
--- PASS: TestAccBigipLtmPersistenceProfileCookieCreate (5.68s)
=== RUN   TestAccBigipLtmPersistenceProfileCookieImport
--- PASS: TestAccBigipLtmPersistenceProfileCookieImport (5.71s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrCreate (5.77s)
=== RUN   TestAccBigipLtmPersistenceProfileDstAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileDstAddrImport (5.63s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrCreate
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrCreate (5.89s)
=== RUN   TestAccBigipLtmPersistenceProfileSrcAddrImport
--- PASS: TestAccBigipLtmPersistenceProfileSrcAddrImport (5.85s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLCreate
--- PASS: TestAccBigipLtmPersistenceProfileSSLCreate (5.87s)
=== RUN   TestAccBigipLtmPersistenceProfileSSLImport
--- PASS: TestAccBigipLtmPersistenceProfileSSLImport (5.80s)
=== RUN   TestAccBigipLtmPolicy_create
--- PASS: TestAccBigipLtmPolicy_create (9.54s)
=== RUN   TestAccBigipLtmPolicy_import
--- PASS: TestAccBigipLtmPolicy_import (11.82s)
=== RUN   TestAccBigipLtmPool_create
--- PASS: TestAccBigipLtmPool_create (12.28s)
=== RUN   TestAccBigipLtmPool_import
--- PASS: TestAccBigipLtmPool_import (10.61s)
=== RUN   TestAccBigipLtmfasthttp_create
--- PASS: TestAccBigipLtmfasthttp_create (7.01s)
=== RUN   TestAccBigipLtmProfilefasthttp_import
--- PASS: TestAccBigipLtmProfilefasthttp_import (5.28s)
=== RUN   TestAccBigipLtmProfileFastl4_create
--- PASS: TestAccBigipLtmProfileFastl4_create (5.47s)
=== RUN   TestAccBigipLtmProfileFastl4_import
--- PASS: TestAccBigipLtmProfileFastl4_import (5.27s)
=== RUN   TestAccBigipLtmProfileHttp2_create
--- PASS: TestAccBigipLtmProfileHttp2_create (4.94s)
=== RUN   TestAccBigipLtmProfileHttp2_import
--- PASS: TestAccBigipLtmProfileHttp2_import (4.91s)
=== RUN   TestAccBigipLtmProfileHttpcompress_create
--- PASS: TestAccBigipLtmProfileHttpcompress_create (5.20s)
=== RUN   TestAccBigipLtmProfileHttpcompress_import
--- PASS: TestAccBigipLtmProfileHttpcompress_import (5.05s)
=== RUN   TestAccBigipLtmProfileoneconnect_create
--- PASS: TestAccBigipLtmProfileoneconnect_create (4.99s)
=== RUN   TestAccBigipLtmProfileoneconnect_import
--- PASS: TestAccBigipLtmProfileoneconnect_import (5.04s)
=== RUN   TestAccBigipLtmProfileTcp_create
--- PASS: TestAccBigipLtmProfileTcp_create (4.89s)
=== RUN   TestAccBigipLtmProfileTcp_import
--- PASS: TestAccBigipLtmProfileTcp_import (5.04s)
=== RUN   TestAccBigipLtmsnat_create
--- PASS: TestAccBigipLtmsnat_create (5.02s)
=== RUN   TestAccBigipLtmsnat_import
--- PASS: TestAccBigipLtmsnat_import (4.98s)
=== RUN   TestAccBigipLtmsnatpool_create
--- PASS: TestAccBigipLtmsnatpool_create (5.13s)
=== RUN   TestAccBigipLtmsnatpool_import
--- PASS: TestAccBigipLtmsnatpool_import (4.96s)
=== RUN   TestAccBigipLtmVA_create
--- PASS: TestAccBigipLtmVA_create (5.29s)
=== RUN   TestAccBigipLtmVA_import
--- PASS: TestAccBigipLtmVA_import (5.39s)
=== RUN   TestAccBigipLtmVS_create
--- PASS: TestAccBigipLtmVS_create (9.21s)
=== RUN   TestAccBigipLtmVS_import
--- PASS: TestAccBigipLtmVS_import (9.21s)
=== RUN   TestAccBigipNetroute_create
--- PASS: TestAccBigipNetroute_create (6.81s)
=== RUN   TestAccBigipNetroute_import
--- PASS: TestAccBigipNetroute_import (6.81s)
=== RUN   TestAccBigipNetselfip_create
--- PASS: TestAccBigipNetselfip_create (6.17s)
=== RUN   TestAccBigipNetselfip_import
--- PASS: TestAccBigipNetselfip_import (6.04s)
=== RUN   TestAccBigipNetvlan_create
--- PASS: TestAccBigipNetvlan_create (5.17s)
=== RUN   TestAccBigipNetvlan_import
--- PASS: TestAccBigipNetvlan_import (5.22s)
=== RUN   TestAccBigipSysdns_create
--- PASS: TestAccBigipSysdns_create (5.18s)
=== RUN   TestAccBigipSysdns_import
--- PASS: TestAccBigipSysdns_import (5.25s)
=== RUN   TestAccBigipSysIapp_create
--- FAIL: TestAccBigipSysIapp_create (2.20s)
        testing.go:518: Step 0 error: Error applying: 1 error occurred:

                * bigip_sys_iapp.test-iapp: 1 error occurred:

                * bigip_sys_iapp.test-iapp: script did not successfully complete: (invalid command name "source"
                    while executing
                "source /usr/share/compat-tcl8.4/base64/base64.tcl"
                    ("package ifneeded" script)
                    invoked from within
                "package require base64" line:6)
=== RUN   TestAccBigipSysIapp_import
--- FAIL: TestAccBigipSysIapp_import (1.33s)
        testing.go:518: Step 0 error: Error applying: 1 error occurred:

                * bigip_sys_iapp.test-iapp: 1 error occurred:

                * bigip_sys_iapp.test-iapp: script did not successfully complete: (invalid command name "source"
                    while executing
                "source /usr/share/compat-tcl8.4/base64/base64.tcl"
                    ("package ifneeded" script)
                    invoked from within
                "package require base64" line:6)
=== RUN   TestAccBigipSysNtp_create
--- PASS: TestAccBigipSysNtp_create (5.15s)
=== RUN   TestAccBigipSysNtp_import
--- PASS: TestAccBigipSysNtp_import (5.34s)
=== RUN   TestAccBigipSysNtpInvalid
--- PASS: TestAccBigipSysNtpInvalid (0.03s)
=== RUN   TestAccBigipSysProvision_create
--- PASS: TestAccBigipSysProvision_create (4.43s)
=== RUN   TestAccBigipSysProvision_import
--- PASS: TestAccBigipSysProvision_import (4.54s)
=== RUN   TestAccBigipSyssnmp_create
--- PASS: TestAccBigipSyssnmp_create (5.93s)
=== RUN   TestAccBigipSyssnmp_import
--- PASS: TestAccBigipSyssnmp_import (5.43s)
```

**Comment by scshitole** [comment]
@dannyk81 I am reverting this time being as the build is broken will revert back once we complete the go-big package for data group.

**Comment by dannyk81** [comment]
@scshitole Please take a look at https://github.com/f5devcentral/go-bigip/pull/10

This adds the missing `GetInternalDataGroup` function that fixes this issue.

Can you please merge it there?

**Pull request merged**
